import "@/styles/variables.css";
import "@/styles/layouts.css";
import "@/styles/globals.css";
import type { Metadata } from "next";
import AuthSession from "@/components/AuthSession";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="es">
            <body>
                <AuthSession>{children}</AuthSession>
            </body>
        </html>
    );
}
